name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Node ${{ matrix.node }} • ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install root deps (runs postinstall to install subprojects)
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run backend tests
        run: npm run test:backend
        env:
          CI: true

      - name: Run frontend unit tests
        run: npm run test:frontend
        env:
          CI: true

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run frontend e2e tests (Playwright)
        run: npm run test:e2e --prefix frontend
        env:
          CI: true
